import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ClientOnly from './components/ClientOnly'
import Navbar from './components/navbar/Navbar'
import Modal from './components/modals/modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          {/* isOpen={true} */}
          <Modal actionLabel="Submit" title="Hello" isOpen />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
